version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: izusu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    environment:
      DATABASE_URL: "postgres://postgres:123123@postgres:5432/izusu_db"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command:
      [
        "sh",
        "-c",
        "npx prisma generate && npx prisma migrate dev && npm run dev",
      ]

volumes:
  postgres_data:
