import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/style/globals.css";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import { QueryProvider } from "@/providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Order System",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-50">
          <Header />
          <QueryProvider>
            <main className="container mx-auto px-4 py-6">{children}</main>
          </QueryProvider>
          <Footer />
          <Toaster />
        </div>
      </body>
    </html>
  );
}
